# Generated by Django 4.1.3 on 2023-01-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App3D', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
